package com.aqs.pm.cheesyairlines;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import java.nio.charset.StandardCharsets;
import java.util.Locale;

public class FragmentActivity extends AppCompatActivity implements View.OnClickListener {
    Bundle bundle;
    @SuppressLint("SetTextI18n")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_fragment);

        // Instantiate bundle and get the information provided from previous classes
        bundle = getIntent().getBundleExtra("bundle");

        // Harvesting and setText for the message with info
        String sir = bundle.getString("sir");
        String name = bundle.getString("name");
        String from = bundle.getString("from");
        String to = bundle.getString("to");
        String dateDeparture = bundle.getString("dateDeparture");
        String dateDestination = bundle.getString("dateDestination");

        TextView tvPurchase = findViewById(R.id.tvPurchaseFragment);
        tvPurchase.setText(sir + name + ", your travel from " + from + " to " + to + " have been purchased." + "\n\n" +
                "Departure date: " + dateDeparture + "\n" + "Arrival date: " + dateDestination);

        // Set price with createSeed method (at line 118) providing to it 'from' and 'to' data
        TextView tvPrice = findViewById(R.id.tvPrice);
        int price = createSeed(from+to);
        tvPrice.setText("Price:\n"+price+"€");

        // Harvesting of checked related buttons
        String first = bundle.getString("first");
        String pet = bundle.getString("pet");
        String window = bundle.getString("window");
        String breakfast = bundle.getString("break");
        String lunch = bundle.getString("lunch");
        String dinner = bundle.getString("dinner");
        String rbYes = bundle.getString("rdyes");
        String mobility = bundle.getString("mobility");

        // We check if the data provided from OnCheckedChanged is null, in true case we clear it
        if (first == null) {
            first = "";
        }

        if (pet == null) {
            pet = "";
        }

        if (window == null) {
            window = "";
        }

        if (breakfast == null) {
            breakfast = "";
        }

        if (lunch == null) {
            lunch = "";
        }

        if (dinner == null) {
            dinner = "";
        }

        if (rbYes == null) {
            rbYes = "";
        }

        if (mobility == null) {
            mobility = "";
        }

        // SetText for the receipt, dates and we thanks the user for purchase it
        TextView tvReceipt = findViewById(R.id.tvReceiptBody);
        tvReceipt.setText(first + "\n" +
                pet + "\n" +
                window + "\n" +
                breakfast + "\n" +
                lunch + "\n" +
                dinner + "\n" +
                rbYes + "\n" +
                mobility);

        TextView tvDates = findViewById(R.id.tvDates);
        tvDates.setText("Departure date: " + dateDeparture + "\n" + "Arrival date: " + dateDestination);

        TextView tvThanks = findViewById(R.id.tvThanks);
        tvThanks.setText("Thanks " + sir + name + " for your purchase!");

        TextView tvFlightDeparture = findViewById(R.id.tvFlightDeparture);
        tvFlightDeparture.setText(from);

        TextView tvFlightDestination = findViewById(R.id.tvFlightDestination);
        tvFlightDestination.setText(to);

        //Button for go back to MainActivity
        Button btFinal = findViewById(R.id.btFinal);
        btFinal.setOnClickListener(this);

    }

    //Method onClick generated by setOnClickListener that makes action for go back to MainActivity
    @Override
    public void onClick(View view) {
        Intent intent = new Intent(view.getContext(), MainActivity.class);
        view.getContext().startActivity(intent);
    }

    // Method that simulates price, it receives a String and get it bytes - 50, the result is the price
    // but before returns it we check if is too much or negative
    private int createSeed (String seedText) {
        int seedPrice = 0;
        seedText = seedText.toLowerCase(Locale.ROOT);
        for (int i = 0; i < seedText.length(); i++) {
            seedPrice += seedText.getBytes(StandardCharsets.UTF_8)[i]-50;
            System.out.println(seedPrice);

        }
        System.out.println(seedPrice + " final");
        if (seedPrice < 0){
            return 50;
        }

        if (seedPrice > 1000) {
            return 999;
        }


        return seedPrice;
    }
}