package com.aqs.pm.cheesyairlines;

import androidx.appcompat.app.AppCompatActivity;

import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.TextView;

import java.nio.charset.StandardCharsets;
import java.util.Locale;

public class SecondActivity extends AppCompatActivity implements View.OnClickListener {


    Bundle bundle;
    @SuppressLint("SetTextI18n")
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second);

        // Instantiate bundle and get the information provided from previous classes
        bundle = getIntent().getBundleExtra("bundle");

        // Harvesting and setText for the message with info
        String sir = bundle.getString("sir");
        String name = bundle.getString("name");
        String from = bundle.getString("from");
        String to = bundle.getString("to");
        String dateDeparture = bundle.getString("dateDeparture");
        String dateDestination = bundle.getString("dateDestination");
        TextView tvPurchase = findViewById(R.id.tv_purchase);
        tvPurchase.setText(sir + name + ", your travel from " + from + " to " + to + " have been purchased." + "\n\n" +
                "Departure date: " + dateDeparture + "\n" + "Arrival date: " + dateDestination);

        // Instantiate buttons and onClickListener for go to MainActivity or continue to purchase
        Button btBack = findViewById(R.id.btBack);
        btBack.setOnClickListener(this);

        Button btNext = findViewById(R.id.btNext);
        btNext.setOnClickListener(this);

        // Set price with createSeed method (at line 69) providing to it 'from' and 'to' data
        TextView tvPrice = findViewById(R.id.tvPrice);
        int price = createSeed(from+to);
        tvPrice.setText("Price:\n"+price+"€");
    }

    // Method generated by setonClickListener, we set action for go to MainActivity or continue to purchase
    @SuppressLint("NonConstantResourceId")
    @Override
    public void onClick(View view) {
        switch (view.getId()){
            case R.id.btBack:
                finish();
                break;
            case R.id.btNext:
                Context context = view.getContext();
                Intent intent = new Intent(context, ThirdActivity.class);
                intent.putExtra("bundle", bundle);
                context.startActivity(intent);
                break;
        }
    }

    // Method that simulates price, it receives a String and get it bytes - 50, the result is the price
    // but before returns it we check if is too much or negative
    private int createSeed (String seedText) {
        int seedPrice = 0;
        seedText = seedText.toLowerCase(Locale.ROOT);
        for (int i = 0; i < seedText.length(); i++) {
            seedPrice += seedText.getBytes(StandardCharsets.UTF_8)[i]-50;
        }
        System.out.println(seedPrice + " final");
        if (seedPrice < 0){
            return 50;
        }
        if (seedPrice > 1000) {
            return 999;
        }
        return seedPrice;
    }
}